# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0026_auto_20180510_0845'),
        ('eprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='number_of_imports',
        ),
        migrations.AddField(
            model_name='import',
            name='imported_articles',
            field=models.ManyToManyField(to='submission.Article'),
        ),
    ]
