# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0031_field_display'),
        ('eprints', '0002_auto_20180713_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='importedarticleauthor',
            unique_together=set([('article', 'author')]),
        ),
    ]
