# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0031_field_display'),
        ('eprints', '0003_auto_20190227_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedArticleGalley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eprint_id', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('uri', models.URLField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
            ],
        ),
    ]
